export enum ExceptionCode {
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',

  VALIDATION_ERROR = 'VALIDATION_ERROR',

  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',

  CONFLICT = 'CONFLICT',

  UNAUTHORIZED = 'UNAUTHORIZED',

  FORBIDDEN = 'FORBIDDEN',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}