import {
  BarChart3,
  Bell,
  BookOpen,
  CalendarDays,
  ContactRound,
  CreditCard,
  Dumbbell,
  FileChartColumn,
  GitBranch,
  GraduationCap,
  LayoutDashboard,
  Mic2,
  Package,
  ScanLine,
  ScrollText,
  Settings,
  ShieldCheck,
  UserCheck,
  Users,
  Users2,
} from 'lucide-react';

import type { NavigationGroup } from './navigation.types';
import { PATHS } from '@/routes/paths';

export const CORE_NAV_GROUPS: NavigationGroup[] = [
  {
    key: 'workspace',
    label: 'Workspace',
    items: [
      {
        key: 'dashboard',
        href: PATHS.dashboard,
        label: 'Overview',
        icon: LayoutDashboard,
      },
      {
        key: 'contacts',
        href: '/dashboard/contacts',
        label: 'Contacts',
        icon: ContactRound,
        permission: 'contact:read',
        moduleKey: 'contacts',
      },
      {
        key: 'bookings',
        href: '/dashboard/bookings',
        label: 'Bookings',
        icon: CalendarDays,
        permission: 'booking:read',
        moduleKey: 'bookings',
      },
      {
        key: 'payments',
        href: '/dashboard/payments',
        label: 'Payments',
        icon: CreditCard,
        permission: 'payment:read',
        moduleKey: 'payments',
      },
      {
        key: 'inventory',
        href: '/dashboard/inventory',
        label: 'Inventory',
        icon: Package,
        permission: 'inventory:read',
        moduleKey: 'inventory',
      },
      {
        key: 'reports',
        href: '/dashboard/reports',
        label: 'Reports',
        icon: BarChart3,
        permission: 'report:read',
        moduleKey: 'reports',
      },
      {
        key: 'enquiries',
        href: '/dashboard/enquiries',
        label: 'Enquiries',
        icon: ContactRound,
        moduleKey: 'enquiries',
      },
    ],
  },
  {
    key: 'organisation',
    label: 'Organisation',
    items: [
      {
        key: 'branches',
        href: PATHS.branches,
        label: 'Branches',
        icon: GitBranch,
        permission: 'branch:read',
        moduleKey: 'multiBranch',
      },
      {
        key: 'users',
        href: PATHS.users,
        label: 'People',
        icon: Users,
        permission: 'user:read',
      },
      {
        key: 'roles',
        href: PATHS.roles,
        label: 'Roles & access',
        icon: ShieldCheck,
        permission: 'user:role-assign',
      },
    ],
  },
  {
    key: 'system',
    label: 'System',
    items: [
      {
        key: 'notifications',
        href: PATHS.notifications,
        label: 'Notifications',
        icon: Bell,
        moduleKey: 'notifications',
        badge: 'count',
      },
      {
        key: 'audit-log',
        href: PATHS.auditLog,
        label: 'Audit log',
        icon: ScrollText,
        permission: 'organization:read',
        moduleKey: 'auditLog',
      },
      {
        key: 'settings',
        href: PATHS.settings,
        label: 'Settings',
        icon: Settings,
        permission: 'organization:read',
      },
    ],
  },
];

export const MUSIC_ORG_NAV_GROUPS: NavigationGroup[] = [
  {
    key: 'academy',
    label: 'Academy',
    items: [
      {
        key: 'students',
        href: PATHS.music.students,
        label: 'Students',
        icon: GraduationCap,
        permission: 'music:student-read',
        industry: 'MUSIC_ORG',
        moduleKey: 'musicOrg',
      },
      {
        key: 'teachers',
        href: PATHS.music.teachers,
        label: 'Teachers',
        icon: Mic2,
        permission: 'music:teacher-read',
        industry: 'MUSIC_ORG',
        moduleKey: 'musicOrg',
      },
      {
        key: 'courses',
        href: PATHS.music.courses,
        label: 'Courses',
        icon: BookOpen,
        permission: 'music:course-read',
        industry: 'MUSIC_ORG',
        moduleKey: 'musicOrg',
      },
      {
        key: 'batches',
        href: PATHS.music.batches,
        label: 'Batches',
        icon: Users2,
        permission: 'music:batch-read',
        industry: 'MUSIC_ORG',
        moduleKey: 'musicOrg',
      },
      {
        key: 'calendar',
        href: PATHS.music.calendar,
        label: 'Calendar',
        icon: CalendarDays,
        permission: 'music:student-read',
        industry: 'MUSIC_ORG',
        moduleKey: 'musicOrg',
      },
      {
        key: 'subscriptions',
        href: PATHS.music.subscriptions,
        label: 'Subscriptions',
        icon: CreditCard,
        permission: 'music:subscription-read',
        industry: 'MUSIC_ORG',
        moduleKey: 'musicOrg',
      },
    ],
  },
  ...CORE_NAV_GROUPS,
];

export const GYM_NAV_GROUPS: NavigationGroup[] = [
  {
    key: 'gym',
    label: 'Gym',
    items: [
      {
        key: 'members',
        href: PATHS.gym.members,
        label: 'Members',
        icon: Users,
        permission: 'gym:member-read',
        industry: 'GYM',
        moduleKey: 'gym',
      },
      {
        key: 'classes',
        href: PATHS.gym.classes,
        label: 'Classes',
        icon: Dumbbell,
        permission: 'gym:class-read',
        industry: 'GYM',
        moduleKey: 'gym',
      },
      {
        key: 'trainers',
        href: PATHS.gym.trainers,
        label: 'Trainers',
        icon: UserCheck,
        permission: 'gym:trainer-read',
        industry: 'GYM',
        moduleKey: 'gym',
      },
      {
        key: 'memberships',
        href: PATHS.gym.memberships,
        label: 'Memberships',
        icon: FileChartColumn,
        permission: 'gym:membership-read',
        industry: 'GYM',
        moduleKey: 'gym',
      },
      {
        key: 'attendance',
        href: PATHS.gym.attendance,
        label: 'Attendance',
        icon: ScanLine,
        permission: 'gym:attendance-read',
        industry: 'GYM',
        moduleKey: 'gym',
      },
    ],
  },
  ...CORE_NAV_GROUPS,
];
